# Generated by Django 6.0.5 on 2026-06-15 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotos', '0007_search_trigram_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machinetranslationcache',
            options={'ordering': ['-hits', '-id']},
        ),
        migrations.AlterField(
            model_name='pinvariant',
            name='kind',
            field=models.CharField(choices=[('story', 'Story'), ('square', 'Square'), ('landscape', 'Landscape'), ('feed', 'Feed thumbnail')], max_length=20),
        ),
    ]
