# Generated by Django 6.0.4 on 2026-05-09 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_fr', models.CharField(max_length=500, verbose_name='Question (FR)')),
                ('question_en', models.CharField(blank=True, default='', max_length=500, verbose_name='Question (EN)')),
                ('answer_fr', models.TextField(verbose_name='Réponse (FR)')),
                ('answer_en', models.TextField(blank=True, default='', verbose_name='Réponse (EN)')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='Publié')),
                ('related_legal_slug', models.CharField(blank=True, choices=[('', 'Aucun lien'), ('privacy', 'Confidentialité'), ('terms', "Conditions d'utilisation"), ('contact', 'Contact')], default='', max_length=40, verbose_name='Lien « en savoir plus »')),
            ],
            options={
                'verbose_name': 'Entrée FAQ',
                'verbose_name_plural': 'FAQ',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(choices=[('privacy', 'Politique de confidentialité'), ('terms', "Conditions d'utilisation"), ('contact', 'Contact')], max_length=40, unique=True)),
                ('title_fr', models.CharField(blank=True, default='', max_length=500, verbose_name='Titre (FR)')),
                ('title_en', models.CharField(blank=True, default='', max_length=500, verbose_name='Titre (EN)')),
                ('body_fr', models.TextField(blank=True, default='')),
                ('body_en', models.TextField(blank=True, default='')),
                ('contact_email', models.EmailField(blank=True, default='', help_text='Utilisé pour la page « contact » (mailto).', max_length=254, verbose_name='E-mail de contact')),
                ('translations_cache', models.JSONField(blank=True, default=dict, help_text='Rempli automatiquement (googletrans), ex. {"es": {"title": "…", "body": "…"}}.', verbose_name='Cache traductions')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page publique (légal / contact)',
                'verbose_name_plural': 'Pages publiques (légal / contact)',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('color', models.CharField(default='#6B7280', max_length=80)),
                ('icon', models.CharField(default='category', max_length=50)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='topic_covers/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TopicTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=120, unique=True)),
                ('translations', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['topic'],
            },
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_private', models.BooleanField(default=False)),
                ('share_token', models.UUIDField(blank=True, editable=False, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collaborators', models.ManyToManyField(blank=True, related_name='collaborative_boards', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('link', models.URLField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pins/')),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('followers', 'Followers'), ('private', 'Private')], default='public', max_length=20)),
                ('comments_policy', models.CharField(choices=[('open', 'Open'), ('followers_only', 'Followers only'), ('closed', 'Closed')], default='open', max_length=24)),
                ('certified_credit', models.BooleanField(default=False)),
                ('provenance_root_hash', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('scheduled_publish_at', models.DateTimeField(blank=True, null=True)),
                ('is_story', models.BooleanField(default=False)),
                ('story_ephemeral', models.BooleanField(db_index=True, default=False)),
                ('story_expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('story_video', models.FileField(blank=True, null=True, upload_to='story_videos/')),
                ('needs_review', models.BooleanField(default=False)),
                ('report_count', models.PositiveIntegerField(default=0)),
                ('moderation_hidden', models.BooleanField(default=False)),
                ('media_sensitive_blur', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to=settings.AUTH_USER_MODEL)),
                ('hashtags', models.ManyToManyField(blank=True, related_name='pins', to='pins.hashtag')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden_by_owner', models.BooleanField(default=False)),
                ('text', models.TextField()),
                ('gif_url', models.URLField(blank=True, null=True)),
                ('media', models.ImageField(blank=True, null=True, upload_to='comments/')),
                ('mentions', models.JSONField(blank=True, default=list)),
                ('original_language', models.CharField(default='auto', max_length=8)),
                ('translated_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('needs_review', models.BooleanField(default=False)),
                ('report_count', models.PositiveIntegerField(default=0)),
                ('moderation_hidden', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='pins.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('hashtags', models.ManyToManyField(blank=True, related_name='comments', to='pins.hashtag')),
                ('pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='pins.pin')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PinBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pin_board_memberships', to='pins.board')),
                ('pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pin_board_memberships', to='pins.pin')),
            ],
            options={
                'ordering': ['position', 'id'],
                'unique_together': {('pin', 'board')},
            },
        ),
        migrations.AddField(
            model_name='pin',
            name='boards',
            field=models.ManyToManyField(blank=True, related_name='pins', through='pins.PinBoard', to='pins.board'),
        ),
        migrations.CreateModel(
            name='PinEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', models.JSONField(blank=True, default=list)),
                ('embedding_dim', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding_profile', to='pins.pin')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PinProvenanceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('edit', 'Edit'), ('save', 'Save'), ('repost', 'Repost')], default='create', max_length=20)),
                ('previous_hash', models.CharField(blank=True, max_length=128)),
                ('current_hash', models.CharField(max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provenance_events', to=settings.AUTH_USER_MODEL)),
                ('pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provenance_events', to='pins.pin')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PinViewEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_events', to='pins.pin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pin_view_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='pin',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pins', to='pins.topic'),
        ),
        migrations.CreateModel(
            name='UserEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', models.JSONField(blank=True, default=list)),
                ('embedding_dim', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='BoardCollaborationInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaboration_invites', to='pins.board')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_collab_invites_sent', to=settings.AUTH_USER_MODEL)),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_collab_invites_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('board', 'invitee'), name='unique_board_collab_invitee')],
            },
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to='pins.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'comment')},
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='pins.pin')),
            ],
            options={
                'unique_together': {('user', 'pin')},
            },
        ),
        migrations.CreateModel(
            name='ContentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('spam', 'Spam ou publicité'), ('harassment', 'Harcèlement ou intimidation'), ('hate', 'Haine ou discrimination'), ('sexual', 'Contenu sexuel ou nudité non autorisée'), ('violence', 'Violence ou danger'), ('illegal', 'Activité illégale'), ('minor', 'Sécurité des mineurs'), ('impersonation', 'Usurpation ou arnaque'), ('copyright', 'Propriété intellectuelle'), ('other', 'Autre')], default='other', max_length=32)),
                ('details', models.TextField(blank=True)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='pins.comment')),
                ('reported_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_reports_received', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_reports', to=settings.AUTH_USER_MODEL)),
                ('pin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='pins.pin')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['pin', '-created_at'], name='pins_conten_pin_id_5ebb3e_idx'), models.Index(fields=['comment', '-created_at'], name='pins_conten_comment_675401_idx'), models.Index(fields=['reported_user', '-created_at'], name='pins_conten_reporte_4034bf_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('comment__isnull', True), ('pin__isnull', False), ('reported_user__isnull', True)), models.Q(('comment__isnull', False), ('pin__isnull', True), ('reported_user__isnull', True)), models.Q(('comment__isnull', True), ('pin__isnull', True), ('reported_user__isnull', False)), _connector='OR'), name='contentreport_exactly_one_target'), models.UniqueConstraint(condition=models.Q(('reported_user__isnull', False)), fields=('reporter', 'reported_user'), name='contentreport_unique_profile_per_reporter'), models.UniqueConstraint(condition=models.Q(('pin__isnull', False)), fields=('reporter', 'pin'), name='contentreport_unique_pin_per_reporter'), models.UniqueConstraint(condition=models.Q(('comment__isnull', False)), fields=('reporter', 'comment'), name='contentreport_unique_comment_per_reporter')],
            },
        ),
        migrations.CreateModel(
            name='PinVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('story', 'Story'), ('square', 'Square'), ('landscape', 'Landscape')], max_length=20)),
                ('image', models.ImageField(upload_to='pins/variants/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_assets', to='pins.pin')),
            ],
            options={
                'ordering': ['kind'],
                'unique_together': {('pin', 'kind')},
            },
        ),
        migrations.CreateModel(
            name='PrivatePinTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_tags', to='pins.pin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_pin_tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['tag'],
                'unique_together': {('user', 'pin', 'tag')},
            },
        ),
        migrations.CreateModel(
            name='Save',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='pins.pin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'pin')},
            },
        ),
        migrations.CreateModel(
            name='TagInvisible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('confidence', models.FloatField(default=0.0)),
                ('source', models.CharField(default='auto', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invisible_tags', to='pins.pin')),
            ],
            options={
                'ordering': ['-confidence', 'tag'],
                'unique_together': {('pin', 'tag')},
            },
        ),
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('view', 'View'), ('like', 'Like'), ('click', 'Click'), ('save', 'Save'), ('creator_visit', 'Creator Visit')], max_length=20)),
                ('dwell_seconds', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_interactions', to=settings.AUTH_USER_MODEL)),
                ('pin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_interactions', to='pins.pin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pin_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='pins_userin_user_id_370fa2_idx'), models.Index(fields=['event_type', '-created_at'], name='pins_userin_event_t_22a484_idx')],
            },
        ),
    ]
