# Generated by Django 6.0.4 on 2026-04-08 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0003_save'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='topic',
            field=models.CharField(default='Général', max_length=100),
        ),
    ]
