# Generated by Django 6.0.4 on 2026-04-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0005_board_pin_boards'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, unique=True),
        ),
    ]
