# Generated by Django 6.0.4 on 2026-04-30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0006_pin_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='pin',
            name='visibility',
            field=models.CharField(
                choices=[('public', 'Public'), ('followers', 'Followers'), ('private', 'Private')],
                default='public',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='pin',
            name='certified_credit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pin',
            name='provenance_root_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='pin',
            name='hashtags',
            field=models.ManyToManyField(blank=True, related_name='pins', to='pins.hashtag'),
        ),
        migrations.AddField(
            model_name='comment',
            name='gif_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='mentions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='comment',
            name='original_language',
            field=models.CharField(default='auto', max_length=8),
        ),
        migrations.AddField(
            model_name='comment',
            name='translated_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='replies',
                to='pins.comment',
            ),
        ),
        migrations.AddField(
            model_name='comment',
            name='hashtags',
            field=models.ManyToManyField(blank=True, related_name='comments', to='pins.hashtag'),
        ),
        migrations.CreateModel(
            name='PinProvenanceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('edit', 'Edit'), ('save', 'Save'), ('repost', 'Repost')], default='create', max_length=20)),
                ('previous_hash', models.CharField(blank=True, max_length=128)),
                ('current_hash', models.CharField(max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provenance_events', to=settings.AUTH_USER_MODEL)),
                ('pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provenance_events', to='pins.pin')),
            ],
            options={'ordering': ['created_at']},
        ),
        migrations.CreateModel(
            name='PrivatePinTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_tags', to='pins.pin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_pin_tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['tag'], 'unique_together': {('user', 'pin', 'tag')}},
        ),
    ]

