# Generated by Django 6.0.4 on 2026-04-30 23:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0007_rich_features'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='board',
            unique_together={('user', 'name')},
        ),
    ]
