# Generated by Django 6.0.4 on 2026-05-03 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0023_legal_document_board_invite'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pin',
            name='pins_pin_sched_pub_idx',
        ),
        migrations.RenameIndex(
            model_name='contentreport',
            new_name='pins_conten_pin_id_5ebb3e_idx',
            old_name='pins_conten_pin_id_a83658_idx',
        ),
        migrations.RenameIndex(
            model_name='contentreport',
            new_name='pins_conten_comment_675401_idx',
            old_name='pins_conten_comment_e83eab_idx',
        ),
    ]
