# Generated by Django 6.0.4 on 2026-05-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0027_contentreport_expand_userblock'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contentreport',
            new_name='pins_conten_reporte_4034bf_idx',
            old_name='pins_conten_reporte_idx',
        ),
        migrations.AlterField(
            model_name='contentreport',
            name='details',
            field=models.TextField(blank=True),
        ),
    ]
