# Generated by Django 6.0.4 on 2026-05-06 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0033_offline_sync_foundation'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='processedaction',
            new_name='pins_proces_user_id_09780b_idx',
            old_name='pins_proces_user_id_d46ce5_idx',
        ),
        migrations.RenameIndex(
            model_name='processedaction',
            new_name='pins_proces_client__3c8740_idx',
            old_name='pins_proces_client__f77315_idx',
        ),
    ]
