# Generated by Django 6.0.4 on 2026-05-09 17:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralAttribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending_email', 'Pending email verification'), ('active', 'Active'), ('revoked', 'Revoked')], db_index=True, default='pending_email', max_length=24)),
                ('source', models.CharField(choices=[('link_query', 'Link query'), ('deep_link', 'Deep link'), ('signup_field', 'Signup field'), ('intent_api', 'Intent API'), ('oauth_completion', 'OAuth completion'), ('onboarding_modal', 'Onboarding modal')], default='signup_field', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('rewards_granted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('signup_ip', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('signup_device_hash', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('referee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_attribution', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_given', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=64)),
                ('ip', models.CharField(blank=True, default='', max_length=64)),
                ('device_hash', models.CharField(blank=True, default='', max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('attribution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='referrals.referralattribution')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralContestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winners_json', models.JSONField(blank=True, default=list)),
                ('leaderboard_snapshot_json', models.JSONField(blank=True, default=list)),
                ('stats_json', models.JSONField(blank=True, default=dict)),
                ('finalized_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('contest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_result', to='contests.contestsettings')),
            ],
            options={
                'ordering': ['-finalized_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralContestSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defer_rewards', models.BooleanField(default=True, help_text='Si activé : aucun point parrain tant que le filleul ne passe pas les garde-fous.')),
                ('min_account_age_hours', models.PositiveIntegerField(default=12, help_text='Âge minimum du compte filleul (h) avant éligibilité aux points.')),
                ('min_engagement_actions', models.PositiveIntegerField(default=1, help_text='Nombre minimum d’interactions concours fotos valides du filleul.')),
                ('reward_delay_hours', models.PositiveIntegerField(default=1, help_text='Délai minimum après validation du filleul avant éligibilité aux points.')),
                ('min_days_before_reward', models.PositiveIntegerField(default=2, help_text='Jours minimum d’activité du filleul avant points parrain.')),
                ('max_signups_per_ip_per_24h', models.PositiveIntegerField(default=40, help_text='Plafond inscriptions avec IP identique sur 24 h.')),
                ('max_signups_per_device_per_24h', models.PositiveIntegerField(default=20, help_text='Plafond inscriptions avec empreinte device identique sur 24 h.')),
                ('max_referrals_per_referrer_per_24h', models.PositiveIntegerField(default=40, help_text='Plafond nouveaux filleuls attribués au même parrain sur 24 h.')),
                ('referee_trust_threshold', models.FloatField(default=0.25, help_text='Trust minimum du filleul (0–1) pour créditer le parrain.')),
                ('min_pins_published', models.PositiveIntegerField(default=0, help_text='Nombre minimum de fotos publics publiés par le filleul (0 = désactivé).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_settings', to='contests.contestsettings')),
            ],
            options={
                'ordering': ['-contest__contest_key'],
            },
        ),
        migrations.CreateModel(
            name='ReferralEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('link_opened', 'Link opened'), ('signup_started', 'Signup started'), ('signup_validated', 'Signup validated'), ('first_login', 'First login'), ('first_post', 'First post'), ('engagement', 'Engagement'), ('retention', 'Retention'), ('retention_progress', 'Retention progress'), ('referral_finalized', 'Referral finalized'), ('reward_deferred', 'Reward deferred'), ('reward_granted', 'Reward granted'), ('fraud_blocked', 'Fraud blocked')], db_index=True, max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_valid', models.BooleanField(db_index=True, default=True)),
                ('invalid_reason', models.CharField(blank=True, default='', max_length=120)),
                ('score_delta', models.FloatField(default=0.0)),
                ('trust_score', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('contest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_events', to='contests.contestsettings')),
                ('referee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_events_as_referee', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_events_as_referrer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralLeaderboardEvent',
            fields=[
                ('sequence', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=32)),
                ('entity_id', models.PositiveIntegerField(db_index=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_leaderboard_events', to='contests.contestsettings')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='ReferralPendingIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('device_binding_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('code_normalized', models.CharField(db_index=True, max_length=32)),
                ('utm_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['session_key', '-created_at'], name='referrals_r_session_3493ac_idx'), models.Index(fields=['device_binding_id', '-created_at'], name='referrals_r_device__9b48d6_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('session_key', ''), ('device_binding_id', ''), _negated=True), name='referral_intent_session_or_device')],
            },
        ),
        migrations.CreateModel(
            name='ReferralSignupContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signup_ip', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('device_hash', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('user_agent_snippet', models.CharField(blank=True, default='', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_signup_context', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralSuspicionFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=64)),
                ('severity', models.PositiveSmallIntegerField(default=1, help_text='1=info, 5=critique')),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], db_index=True, default='open', max_length=16)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('attribution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suspicion_flags', to='referrals.referralattribution')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_suspicion_flags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferrerReferralScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.FloatField(db_index=True, default=0.0)),
                ('rank', models.PositiveIntegerField(db_index=True, default=0)),
                ('previous_rank', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrer_referral_scores', to='contests.contestsettings')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrer_referral_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['rank', '-total_score'],
            },
        ),
        migrations.CreateModel(
            name='UserReferralCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, editable=False, max_length=16, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_code_row', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserReferralTrust',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(db_index=True, default=0.5)),
                ('signals_json', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_trust_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='referralattribution',
            index=models.Index(fields=['referrer', 'status'], name='referrals_r_referre_16d89e_idx'),
        ),
        migrations.AddIndex(
            model_name='referralattribution',
            index=models.Index(fields=['rewards_granted_at'], name='referrals_r_rewards_c52399_idx'),
        ),
        migrations.AddIndex(
            model_name='referralevent',
            index=models.Index(fields=['contest', 'event_type', '-created_at'], name='referrals_r_contest_438911_idx'),
        ),
        migrations.AddIndex(
            model_name='referralevent',
            index=models.Index(fields=['referrer', '-created_at'], name='referrals_r_referre_9cbb73_idx'),
        ),
        migrations.AddIndex(
            model_name='referralsignupcontext',
            index=models.Index(fields=['signup_ip', '-created_at'], name='referrals_r_signup__fcb618_idx'),
        ),
        migrations.AddIndex(
            model_name='referralsignupcontext',
            index=models.Index(fields=['device_hash', '-created_at'], name='referrals_r_device__a939b5_idx'),
        ),
        migrations.AddIndex(
            model_name='referralsuspicionflag',
            index=models.Index(fields=['status', '-created_at'], name='referrals_r_status_d1f7af_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='referrerreferralscore',
            unique_together={('contest', 'referrer')},
        ),
    ]
