# Generated by Django 6.0.5 on 2026-06-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monetization', '0008_boostpackage_kind_and_campaign_catalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinpromocampaign',
            name='media',
            field=models.FileField(blank=True, null=True, storage='monetization.storage.creator_ad_media_storage', upload_to='creator_ads/media/'),
        ),
    ]
