# Generated by Django 6.0.4 on 2026-05-09 17:16

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PinovaSubscriptionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_discount_percent', models.PositiveSmallIntegerField(default=10, help_text='Badge −X\u202f% « annuel » sur la page Premium et valeur API annual_discount_percent. Mettre 0 pour masquer le badge ; les paiements suivent encore les lignes SubscriptionPricing.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration abonnement Pinova',
                'verbose_name_plural': 'Configuration abonnement Pinova',
            },
        ),
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_otp', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('avatar_color', models.CharField(default='bg-blue-500', max_length=50)),
                ('subscription_plan', models.CharField(choices=[('free', 'Free'), ('plus', 'Plus'), ('pro', 'Pro')], default='free', max_length=20)),
                ('subscription_renewal_at', models.DateTimeField(blank=True, null=True)),
                ('translation_quota_monthly', models.PositiveIntegerField(default=5)),
                ('translation_used_monthly', models.PositiveIntegerField(default=0)),
                ('discoverable_profile', models.BooleanField(default=True)),
                ('allow_ai_translation', models.BooleanField(default=True)),
                ('preferred_language', models.CharField(default='fr', max_length=10)),
                ('preferred_currency', models.CharField(default='XOF', max_length=3)),
                ('country_code', models.CharField(blank=True, default='', max_length=2)),
                ('tips_enabled', models.BooleanField(default=False)),
                ('tips_url', models.URLField(blank=True, null=True)),
                ('private_profile', models.BooleanField(default=False)),
                ('notifications_followers', models.BooleanField(default=True)),
                ('notifications_saves', models.BooleanField(default=True)),
                ('notifications_recommendations', models.BooleanField(default=False)),
                ('notifications_digest_creator_weekly', models.BooleanField(default=True)),
                ('subscription_cancel_at_period_end', models.BooleanField(default=False)),
                ('subscription_scheduled_plan', models.CharField(blank=True, choices=[('free', 'Free'), ('plus', 'Plus'), ('pro', 'Pro')], default='', max_length=20)),
                ('share_token', models.UUIDField(blank=True, editable=False, null=True, unique=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('account_scheduled_deletion_at', models.DateTimeField(blank=True, null=True)),
                ('subscription_trial_consumed_at', models.DateTimeField(blank=True, null=True)),
                ('subscription_seat_bundle', models.CharField(blank=True, default='solo', max_length=24)),
                ('sensitive_media_blur_by_default', models.BooleanField(default=True)),
                ('hide_sensitive_pins', models.BooleanField(default=False)),
                ('following', models.ManyToManyField(blank=True, related_name='followers', to='accounts.profile')),
                ('subscription_sponsor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provisioned_subscription_seats', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free', 'Free'), ('plus', 'Plus'), ('pro', 'Pro')], max_length=20)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('amount', models.PositiveIntegerField()),
                ('currency_iso', models.CharField(default='XOF', max_length=10)),
                ('fedapay_transaction_id', models.CharField(max_length=64, unique=True)),
                ('fedapay_reference', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('checkout_url', models.URLField(blank=True)),
                ('invoice_url', models.URLField(blank=True, max_length=500)),
                ('promo_bundle', models.CharField(blank=True, default='', max_length=24)),
                ('fedapay_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free', 'Free'), ('plus', 'Plus'), ('pro', 'Pro')], max_length=20)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('seat_bundle', models.CharField(choices=[('solo', 'Solo'), ('family', 'Family'), ('team', 'Team')], default='solo', max_length=24)),
                ('amount', models.PositiveIntegerField()),
                ('duration_days', models.PositiveIntegerField(default=30)),
                ('currency_iso', models.CharField(default='XOF', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['plan', 'billing_cycle', 'seat_bundle'],
                'unique_together': {('plan', 'billing_cycle', 'seat_bundle')},
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=140)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('priority', 'Priority')], default='normal', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionSeatInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(editable=False, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('declined', 'declined'), ('expired', 'expired'), ('revoked', 'revoked')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_invitations_received', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_invitations_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['owner', 'status'], name='accounts_su_owner_i_cc2329_idx'), models.Index(fields=['invitee', 'status'], name='accounts_su_invitee_7b1a3b_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('owner', 'invitee'), name='uniq_pending_seat_invite_owner_invitee')],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionSeatMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_memberships_received', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_memberships_owned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['owner'], name='accounts_su_owner_i_efb4b2_idx'), models.Index(fields=['member'], name='accounts_su_member__abca04_idx')],
                'constraints': [models.UniqueConstraint(fields=('owner', 'member'), name='uniq_subscription_seat_owner_member'), models.UniqueConstraint(fields=('member',), name='uniq_subscription_seat_member_singleton')],
            },
        ),
        migrations.CreateModel(
            name='UserBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_blocks_received', to=settings.AUTH_USER_MODEL)),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_blocks_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['blocker', '-created_at'], name='accounts_us_blocker_1cc77b_idx'), models.Index(fields=['blocked', '-created_at'], name='accounts_us_blocked_44b0d8_idx')],
                'constraints': [models.UniqueConstraint(fields=('blocker', 'blocked'), name='uniq_userblock_blocker_blocked'), models.CheckConstraint(condition=models.Q(('blocker_id', models.F('blocked_id')), _negated=True), name='userblock_no_self')],
            },
        ),
    ]
