# Generated by Django 6.0.4 on 2026-04-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='allow_ai_translation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='discoverable_profile',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='subscription_plan',
            field=models.CharField(choices=[('free', 'Free'), ('plus', 'Plus'), ('pro', 'Pro')], default='free', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='subscription_renewal_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='translation_quota_monthly',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='translation_used_monthly',
            field=models.PositiveIntegerField(default=0),
        ),
    ]

