# Generated by Django 6.0.4 on 2026-05-01 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_preferred_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ad_ads_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='partner_ads_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
