# Generated by Django 6.0.4 on 2026-05-01 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_ad_ads_enabled_profile_partner_ads_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tips_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='tips_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
