# Generated by Django 6.0.4 on 2026-05-03 00:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_pinova_subscription_config'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionpricing',
            options={'ordering': ['plan', 'billing_cycle', 'seat_bundle']},
        ),
        migrations.RenameIndex(
            model_name='subscriptionseatinvitation',
            new_name='accounts_su_owner_i_cc2329_idx',
            old_name='accounts_su_owner_i_61e4e4_idx',
        ),
        migrations.RenameIndex(
            model_name='subscriptionseatinvitation',
            new_name='accounts_su_invitee_7b1a3b_idx',
            old_name='accounts_su_invitee_4d7d5c_idx',
        ),
        migrations.RenameIndex(
            model_name='subscriptionseatmember',
            new_name='accounts_su_owner_i_efb4b2_idx',
            old_name='accounts_su_owner_i_82c3b2_idx',
        ),
        migrations.RenameIndex(
            model_name='subscriptionseatmember',
            new_name='accounts_su_member__abca04_idx',
            old_name='accounts_su_member__b5e8fb_idx',
        ),
        migrations.AlterField(
            model_name='pinovasubscriptionconfig',
            name='annual_discount_percent',
            field=models.PositiveSmallIntegerField(default=10, help_text='Badge −X\u202f% « annuel » sur la page Premium et valeur API annual_discount_percent. Mettre 0 pour masquer le badge ; les paiements suivent encore les lignes SubscriptionPricing.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
    ]
