# Generated by Django 6.0.4 on 2026-05-03 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_userblock'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userblock',
            new_name='accounts_us_blocker_1cc77b_idx',
            old_name='accounts_us_blocker_7a8b2c_idx',
        ),
        migrations.RenameIndex(
            model_name='userblock',
            new_name='accounts_us_blocked_44b0d8_idx',
            old_name='accounts_us_blocked_9d0e1f_idx',
        ),
    ]
