"""
Django settings for pinova_backend project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import warnings
import dj_database_url
from urllib.parse import quote_plus
from pathlib import Path
from django.core.exceptions import ImproperlyConfigured
from corsheaders.defaults import default_headers
from dotenv import load_dotenv
from datetime import timedelta

# Load environment variables from .env file
load_dotenv()

# dj-rest-auth + allauth : comparaison sur AUTHENTICATION_METHOD dépréciée (bruit en tests / runserver).
warnings.filterwarnings(
    'ignore',
    message=r'.*AUTHENTICATION_METHOD is deprecated.*',
    category=UserWarning,
    module='dj_rest_auth.forms',
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY') or os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-dev-only-change-me-not-for-production'
    else:
        raise ImproperlyConfigured(
            'Set DJANGO_SECRET_KEY or SECRET_KEY in the environment when DEBUG=False.'
        )

_allowed_raw = os.environ.get('ALLOWED_HOSTS', '').strip()
if _allowed_raw:
    ALLOWED_HOSTS = [h.strip() for h in _allowed_raw.split(',') if h.strip()]
elif DEBUG:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', '[::1]', '*']
else:
    raise ImproperlyConfigured(
        'ALLOWED_HOSTS must be set (comma-separated hostnames) when DEBUG=False, '
        'e.g. ALLOWED_HOSTS=api.example.com'
    )

_cors_origins = os.environ.get('CORS_ALLOWED_ORIGINS', '').strip()
if _cors_origins:
    CORS_ALLOWED_ORIGINS = [o.strip() for o in _cors_origins.split(',') if o.strip()]
    CORS_ALLOW_ALL_ORIGINS = False
elif DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
else:
    raise ImproperlyConfigured(
        'CORS_ALLOWED_ORIGINS must be set when DEBUG=False (comma-separated origins, '
        'e.g. https://app.example.com). Wildcard CORS with credentials is disabled.'
    )

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = (*default_headers, 'x-pinova-device-binding', 'x-pinova-lang', 'x-request-id')
# Permet au navigateur de lire l’en-tête du compteur notifications (axios / fetch).
CORS_EXPOSE_HEADERS = ['X-Pinova-Unread-Notifications', 'X-Cache', 'X-Request-ID']

_csrf_origins = os.environ.get('CSRF_TRUSTED_ORIGINS', '').strip()
if _csrf_origins:
    CSRF_TRUSTED_ORIGINS = [o.strip() for o in _csrf_origins.split(',') if o.strip()]
elif not DEBUG:
    CSRF_TRUSTED_ORIGINS = list(CORS_ALLOWED_ORIGINS)
else:
    CSRF_TRUSTED_ORIGINS = []

if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'True') == 'True'
    SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', str(60 * 60 * 24 * 365)))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = os.environ.get('SECURE_HSTS_INCLUDE_SUBDOMAINS', 'True') == 'True'
    SECURE_HSTS_PRELOAD = os.environ.get('SECURE_HSTS_PRELOAD', 'False') == 'True'
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'

_csp_cdn = (os.environ.get('MEDIA_CDN_DOMAIN') or os.environ.get('CSP_IMG_CDN_HOST') or '').strip()
_csp_img_src = ["'self'", 'data:']
if _csp_cdn:
    _csp_img_src.append(f'https://{_csp_cdn}')
else:
    _csp_img_src.append('https:')
CONTENT_SECURITY_POLICY = os.environ.get(
    'CONTENT_SECURITY_POLICY',
    '; '.join(
        [
            "default-src 'self'",
            "script-src 'self'",
            f"img-src {' '.join(_csp_img_src)}",
            "style-src 'self' 'unsafe-inline'",
            "font-src 'self' data:",
            "connect-src 'self' https://eu.i.posthog.com https://eu-assets.i.posthog.com",
            "frame-ancestors 'none'",
            "base-uri 'self'",
            "form-action 'self'",
        ]
    ),
)

# Application definition

INSTALLED_APPS = [
    'pinova_backend.apps.PinovaBackendConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.postgres',
    'channels',
    # Third party apps
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',
    'dj_rest_auth',
    'dj_rest_auth.registration',
    # Local apps
    'pins',
    'accounts',
    'notifications',
    'contests',
    'referrals',
    'monetization',
]

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'pinova_backend.middleware.request_id.RequestIdMiddleware',
    'pinova_backend.middleware.security.ContentSecurityPolicyMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'pinova_backend.middleware.access_log.StructuredAccessLogMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'pinova_backend.middleware.media.MediaAccessMiddleware',
    'pinova_backend.middleware.unread_notifications.UnreadNotificationsHeaderMiddleware',
    'pinova_backend.middleware.sentry.SentryApiTimingMiddleware',
]

ROOT_URLCONF = 'pinova_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pinova_backend.wsgi.application'
ASGI_APPLICATION = 'pinova_backend.asgi.application'

_redis_url = (os.environ.get('REDIS_URL') or os.environ.get('PINNOVA_REDIS_URL') or '').strip()
PINNOVA_SHARED_CACHE = bool(_redis_url)
if _redis_url:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                'hosts': [_redis_url],
            },
        },
    }
else:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        },
    }

WS_HEARTBEAT_INTERVAL = 30
WS_STALE_TIMEOUT = 90
WS_LEADERBOARD_CONN_LIMIT = 10
WS_LEADERBOARD_CONN_WINDOW = 60

POSTHOG_API_KEY = (os.environ.get('POSTHOG_API_KEY') or os.environ.get('VITE_POSTHOG_KEY') or '').strip()
POSTHOG_HOST = (os.environ.get('POSTHOG_HOST') or 'https://eu.i.posthog.com').strip().rstrip('/')

SENTRY_DSN = (os.environ.get('SENTRY_DSN') or '').strip()
SENTRY_ENVIRONMENT = os.environ.get('SENTRY_ENVIRONMENT') or ('development' if DEBUG else 'production')
SENTRY_RELEASE = (os.environ.get('SENTRY_RELEASE') or os.environ.get('RENDER_GIT_COMMIT') or '').strip()
SENTRY_TRACES_SAMPLE_RATE = float(os.environ.get('SENTRY_TRACES_SAMPLE_RATE', '0.1'))


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# PostgreSQL si DATABASE_URL (ou variables POSTGRES_*/PG*) est défini ; sinon SQLite local (dev sans Postgres).


def _postgres_url_from_split_env() -> str | None:
    """Construit une URL postgres:// à partir des variables classiques Docker / libpq."""
    host = (os.environ.get('POSTGRES_HOST') or os.environ.get('PGHOST') or '').strip()
    name = (os.environ.get('POSTGRES_DB') or os.environ.get('PGDATABASE') or '').strip()
    user = (os.environ.get('POSTGRES_USER') or os.environ.get('PGUSER') or '').strip()
    if not (host and name and user):
        return None
    password = os.environ.get('POSTGRES_PASSWORD') or os.environ.get('PGPASSWORD') or ''
    port = (os.environ.get('POSTGRES_PORT') or os.environ.get('PGPORT') or '5432').strip() or '5432'
    if password:
        auth = f'{quote_plus(user)}:{quote_plus(password)}'
    else:
        auth = quote_plus(user)
    return f'postgresql://{auth}@{host}:{port}/{quote_plus(name)}'


def _resolved_database_url() -> str | None:
    raw = (os.environ.get('DATABASE_URL') or '').strip()
    if raw:
        return raw
    return _postgres_url_from_split_env()


_db_url = _resolved_database_url()

if _db_url:
    DATABASES = {'default': dj_database_url.parse(_db_url, conn_max_age=600)}
else:
    # Pas de Postgres dans l’env (ni DATABASE_URL ni POSTGRES_*/PG*) : SQLite local pour le dev.
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Cache : Redis si REDIS_URL / PINNOVA_REDIS_URL, sinon LocMem (voir CACHES en fin de fichier).

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_CONFIRM_EMAIL_ON_GET = True
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True
ACCOUNT_ADAPTER = 'accounts.adapter.NoEmailConfirmationAdapter'
SOCIALACCOUNT_ADAPTER = 'accounts.adapter.MySocialAccountAdapter'
SOCIALACCOUNT_AUTO_SIGNUP = True

# Frontend URLs for Emails
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:5174')
API_PUBLIC_URL = (os.environ.get('API_PUBLIC_URL') or os.environ.get('BACKEND_URL') or 'http://localhost:8000').rstrip('/')
# Schéma deep link mobile (pinova://invite?ref=…)
REFERRAL_DEEP_LINK_SCHEME = os.environ.get('REFERRAL_DEEP_LINK_SCHEME', 'pinova').strip() or 'pinova'
# URL_FRONTEND_VERIFY_EMAIL = os.environ.get('FRONTEND_URL', 'http://localhost:5174') + '/verify-email'
URL_FRONTEND_PASSWORD_RESET = FRONTEND_URL + '/password-reset-confirm'

# FedaPay
FEDAPAY_ENV = os.environ.get('FEDAPAY_ENV', 'sandbox')
FEDAPAY_SECRET_KEY = os.environ.get('FEDAPAY_SECRET_KEY', '')
FEDAPAY_CURRENCY_ISO = os.environ.get('FEDAPAY_CURRENCY_ISO', 'XOF')
FEDAPAY_CALLBACK_URL = os.environ.get('FEDAPAY_CALLBACK_URL', FRONTEND_URL + '/premium')
FEDAPAY_WEBHOOK_SECRET = (os.environ.get('FEDAPAY_WEBHOOK_SECRET') or '').strip()

# Pubs réseau (AdSense web / AdMob mobile) — IDs de test Google en DEBUG si non configurés.
_ADMOB_TEST_APP_ANDROID = 'ca-app-pub-3940256099942544~3347511713'
_ADMOB_TEST_APP_IOS = 'ca-app-pub-3940256099942544~1458002511'
_ADMOB_TEST_BANNER = 'ca-app-pub-3940256099942544/6300978111'
_ADSENSE_TEST_CLIENT = 'ca-pub-3940256099942544'
_ADSENSE_TEST_SLOT = '6300978111'


def _network_ad_env(key: str, test_fallback: str = '') -> str:
    val = (os.environ.get(key) or '').strip()
    if val:
        return val
    if DEBUG and test_fallback:
        return test_fallback
    return ''


ADSENSE_CLIENT_ID = _network_ad_env('ADSENSE_CLIENT_ID', _ADSENSE_TEST_CLIENT)
ADSENSE_SLOT_FEED = _network_ad_env('ADSENSE_SLOT_FEED', _ADSENSE_TEST_SLOT)
ADSENSE_SLOT_DETAIL = _network_ad_env('ADSENSE_SLOT_DETAIL', _ADSENSE_TEST_SLOT)
ADMOB_APP_ID_ANDROID = _network_ad_env('ADMOB_APP_ID_ANDROID', _ADMOB_TEST_APP_ANDROID)
ADMOB_APP_ID_IOS = _network_ad_env('ADMOB_APP_ID_IOS', _ADMOB_TEST_APP_IOS)
ADMOB_UNIT_FEED_ANDROID = _network_ad_env('ADMOB_UNIT_FEED_ANDROID', _ADMOB_TEST_BANNER)
ADMOB_UNIT_FEED_IOS = _network_ad_env('ADMOB_UNIT_FEED_IOS', _ADMOB_TEST_BANNER)
ADMOB_UNIT_DETAIL_ANDROID = _network_ad_env('ADMOB_UNIT_DETAIL_ANDROID', _ADMOB_TEST_BANNER)
ADMOB_UNIT_DETAIL_IOS = _network_ad_env('ADMOB_UNIT_DETAIL_IOS', _ADMOB_TEST_BANNER)
NETWORK_AD_FEED_EVERY_N = max(4, int(os.environ.get('NETWORK_AD_FEED_EVERY_N', '10')))

# E-mail : Resend (API) si RESEND_API_KEY est défini, sinon SMTP (sauf EMAIL_BACKEND explicite).
# En DEBUG sans Resend ni identifiants SMTP : console — évite les 500 sur auth/password/reset/ en local.
RESEND_API_KEY = (os.environ.get('RESEND_API_KEY') or '').strip()
_explicit_email_backend = (os.environ.get('EMAIL_BACKEND') or '').strip()
_smtp_configured = bool(
    (os.environ.get('EMAIL_HOST_USER') or '').strip()
    and (os.environ.get('EMAIL_HOST_PASSWORD') or '').strip()
)
if _explicit_email_backend:
    EMAIL_BACKEND = _explicit_email_backend
elif RESEND_API_KEY:
    EMAIL_BACKEND = 'pinova_backend.email_backends.resend.ResendBackend'
elif DEBUG and not _smtp_configured:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = (os.environ.get('DEFAULT_FROM_EMAIL') or '').strip() or EMAIL_HOST_USER
if EMAIL_BACKEND == 'django.core.mail.backends.console.EmailBackend' and not DEFAULT_FROM_EMAIL:
    DEFAULT_FROM_EMAIL = 'pinova-dev@localhost'

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'accounts.password_policy.PinovaPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# Dossier attendu par WhiteNoise en dev/tests (souvent absent car listé dans .gitignore).
try:
    Path(STATIC_ROOT).mkdir(parents=True, exist_ok=True)
except OSError:
    pass

# Évite W004 si le dossier n’existe pas (ex. déploiement Render sans dossier ``static`` versionné).
_static_app_dir = BASE_DIR / 'static'
STATICFILES_DIRS = [_static_app_dir] if _static_app_dir.is_dir() else []

# WhiteNoise storage for production
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_SIGNING_SECRET = os.environ.get('MEDIA_SIGNING_SECRET', SECRET_KEY)
MEDIA_SIGNED_URL_TTL_SECONDS = int(os.environ.get('MEDIA_SIGNED_URL_TTL_SECONDS', '3600'))
# En-tête appliqué par ``media_views.serve_media`` ; dupliquer pour /media/ derrière nginx/CDN.
MEDIA_CACHE_CONTROL = os.environ.get(
    'PINNOVA_MEDIA_CACHE_CONTROL',
    'public, max-age=31536000, immutable',
)
MEDIA_SIGNED_CACHE_CONTROL = os.environ.get(
    'PINNOVA_MEDIA_SIGNED_CACHE_CONTROL',
    'private, max-age=3600',
)

# Uploads — validation magic bytes, re-encodage Pillow, scan ClamAV optionnel
PIN_IMAGE_MAX_SIZE_MB = int(os.environ.get('PIN_IMAGE_MAX_SIZE_MB', '10'))
PIN_IMAGE_JPEG_QUALITY = int(os.environ.get('PIN_IMAGE_JPEG_QUALITY', '85'))
ENABLE_CLAMAV_SCAN = os.environ.get('ENABLE_CLAMAV_SCAN', '').lower() in ('1', 'true', 'yes')
CLAMD_HOST = os.environ.get('CLAMD_HOST', '127.0.0.1')
CLAMD_PORT = int(os.environ.get('CLAMD_PORT', '3310'))
CLAMD_SCAN_TIMEOUT_SECONDS = int(os.environ.get('CLAMD_SCAN_TIMEOUT_SECONDS', '120'))

# Stockage S3 / Cloudflare R2 (optionnel — bucket privé, accès via /media/ + signatures)
USE_S3_MEDIA = os.environ.get('USE_S3_MEDIA', '').lower() in ('1', 'true', 'yes')
if USE_S3_MEDIA:
    AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID', '')
    AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY', '')
    AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME', '')
    AWS_S3_ENDPOINT_URL = os.environ.get('AWS_S3_ENDPOINT_URL', '') or None
    AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME', 'auto')
    AWS_S3_CUSTOM_DOMAIN = os.environ.get('MEDIA_CDN_DOMAIN', '') or None
    AWS_DEFAULT_ACL = 'private'
    AWS_QUERYSTRING_AUTH = False
    AWS_S3_OBJECT_PARAMETERS = {
        'CacheControl': MEDIA_CACHE_CONTROL,
    }
    STORAGES = {
        'default': {
            'BACKEND': 'pinova_backend.media_serving.storage.PinovaMediaStorage',
        },
        'staticfiles': {
            'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
        },
    }
    if AWS_S3_CUSTOM_DOMAIN:
        MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/'

# Social Auth Settings
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': os.environ.get('GOOGLE_CLIENT_ID'),
            'secret': os.environ.get('GOOGLE_CLIENT_SECRET'),
            'key': ''
        },
        # Consentement minimal : openid + userinfo.email + userinfo.profile (pas People API).
        'SCOPE': [
            'openid',
            'https://www.googleapis.com/auth/userinfo.email',
            'https://www.googleapis.com/auth/userinfo.profile',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    },
    'facebook': {
        'APP': {
            'client_id': os.environ.get('FACEBOOK_CLIENT_ID'),
            'secret': os.environ.get('FACEBOOK_CLIENT_SECRET'),
            'key': ''
        },
        'METHOD': 'oauth2',
        'SCOPE': ['email', 'public_profile'],
        'AUTH_PARAMS': {'auth_type': 'rerequest'},
        'INIT_PARAMS': {'cookie': True},
        'FIELDS': [
            'id',
            'first_name',
            'last_name',
            'middle_name',
            'name',
            'name_format',
            'picture',
            'short_name',
            'email'
        ],
        'EXCHANGE_TOKEN': True,
        'VERIFIED_EMAIL': False,
        'VERSION': 'v13.0',
    }
}

# REST Framework Settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'pinova_backend.core.authentication.OptionalJWTAuthentication',
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'EXCEPTION_HANDLER': 'pinova_backend.core.exceptions.pinova_exception_handler',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_THROTTLE_CLASSES': [
        'pinova_backend.security.throttling.AnonIPRateThrottle',
        'pinova_backend.security.throttling.AnonIPSustainedThrottle',
        'pinova_backend.security.throttling.AuthenticatedUserRateThrottle',
        'pinova_backend.security.throttling.AuthenticatedUserSustainedThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        # Par IP pour visiteurs / tokens absents ; surcharger en prod avec Redis si plusieurs workers
        'anon_burst': os.environ.get('API_THROTTLE_ANON_BURST', '120/minute'),
        'anon_sustained': os.environ.get('API_THROTTLE_ANON_SUSTAINED', '8000/day'),
        # Utilisateur authentifié (scraping/API clients loggés)
        'user_burst': os.environ.get('API_THROTTLE_USER_BURST', '300/minute'),
        'user_sustained': os.environ.get('API_THROTTLE_USER_SUSTAINED', '50000/day'),
        'otp_verify': os.environ.get('API_THROTTLE_OTP_VERIFY', '10/minute'),
        'otp_resend': os.environ.get('API_THROTTLE_OTP_RESEND', '3/minute'),
        'webhook': os.environ.get('API_RATELIMIT_WEBHOOK', '100/minute'),
    },
}

# django-ratelimit (auth / webhooks) — partage le cache « default » (Redis recommandé)
RATELIMIT_ENABLE = os.environ.get('RATELIMIT_ENABLE', 'True').lower() in ('1', 'true', 'yes')
RATELIMIT_USE_CACHE = 'default'
API_RATELIMIT_LOGIN = os.environ.get('API_RATELIMIT_LOGIN', '10/minute')
API_RATELIMIT_REGISTER = os.environ.get('API_RATELIMIT_REGISTER', '5/minute')
API_RATELIMIT_PASSWORD_RESET = os.environ.get('API_RATELIMIT_PASSWORD_RESET', '5/minute')
API_RATELIMIT_OTP_VERIFY = os.environ.get('API_RATELIMIT_OTP_VERIFY', '10/minute')
API_RATELIMIT_OTP_RESEND = os.environ.get('API_RATELIMIT_OTP_RESEND', '3/minute')
API_RATELIMIT_WEBHOOK = os.environ.get('API_RATELIMIT_WEBHOOK', '100/minute')

REST_AUTH = {
    'USE_JWT': True,
    'LOGIN_SERIALIZER': 'accounts.serializers.PinovaLoginSerializer',
    'PASSWORD_RESET_SERIALIZER': 'accounts.serializers.PinovaPasswordResetSerializer',
    'SESSION_LOGIN': False,
    # Prod : refresh uniquement cookie HttpOnly (web). Dev : refresh aussi en JSON (localStorage).
    # Surcharge : JWT_AUTH_HTTPONLY=1|0
    'JWT_AUTH_HTTPONLY': (
        os.environ.get('JWT_AUTH_HTTPONLY', '').strip().lower() in ('1', 'true', 'yes')
        if os.environ.get('JWT_AUTH_HTTPONLY', '').strip()
        else not DEBUG
    ),
    'JWT_AUTH_COOKIE': 'pinova-auth',
    'JWT_AUTH_REFRESH_COOKIE': 'pinova-refresh-token',
    'JWT_AUTH_COOKIE_USE_CSRF': False,
    'JWT_AUTH_SAMESITE': 'Lax' if DEBUG else 'None',
    'JWT_AUTH_SECURE': not DEBUG,
    'REGISTER_SERIALIZER': 'accounts.serializers.RegisterSerializer',
    'PASSWORD_RESET_CONFIRM_SERIALIZER': 'accounts.serializers.PinovaPasswordResetConfirmSerializer',
}

# JWT : accès court + refresh 30 jours (override via env).
_jwt_access_minutes = int(os.environ.get('JWT_ACCESS_MINUTES', '60'))
_jwt_refresh_days = int(os.environ.get('JWT_REFRESH_DAYS', '30'))

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=_jwt_access_minutes),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=_jwt_refresh_days),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'TOKEN_REFRESH_SERIALIZER': 'accounts.jwt_serializers.PinovaCookieTokenRefreshSerializer',
}

SESSION_COOKIE_AGE = 60 * 60 * 24 * 365  # 1 an
SESSION_SAVE_EVERY_REQUEST = True
SESSION_COOKIE_SAMESITE = 'Lax' if DEBUG else 'None'
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SAMESITE = 'Lax' if DEBUG else 'None'
CSRF_COOKIE_SECURE = not DEBUG

# Cache feed / stats / rate-limit — Redis recommandé en prod multi-workers.
from pinova_backend.config.cache import build_caches_config

CACHES = build_caches_config(redis_url=_redis_url, debug=DEBUG)

CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', _redis_url or 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', CELERY_BROKER_URL)
CELERY_TASK_ALWAYS_EAGER = os.environ.get('CELERY_TASK_ALWAYS_EAGER', 'False') == 'True'
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = int(os.environ.get('CELERY_TASK_TIME_LIMIT', '300'))
CELERY_TASK_ACKS_LATE = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_RESULT_EXPIRES = int(os.environ.get('CELERY_RESULT_EXPIRES', '86400'))

# Vidéo story / pin : taille minimale du fichier uploadé en Mo (0 ou vide = valeur par défaut 1 ; mettre « 0 » pour désactiver)
_raw_mb_s = (os.environ.get('PIN_STORY_VIDEO_MIN_SIZE_MB') or '').strip()
try:
    PIN_STORY_VIDEO_MIN_SIZE_MB = float(_raw_mb_s) if _raw_mb_s != '' else 1.0
except ValueError:
    PIN_STORY_VIDEO_MIN_SIZE_MB = 1.0

# Taille maximale en Mo (0 désactive la limite maximale ; vide = valeur par défaut 128 Mo)
_raw_mb_max = (os.environ.get('PIN_STORY_VIDEO_MAX_SIZE_MB') or '').strip()
try:
    PIN_STORY_VIDEO_MAX_SIZE_MB = float(_raw_mb_max) if _raw_mb_max != '' else 128.0
except ValueError:
    PIN_STORY_VIDEO_MAX_SIZE_MB = 128.0
if PIN_STORY_VIDEO_MAX_SIZE_MB < 0:
    PIN_STORY_VIDEO_MAX_SIZE_MB = 128.0

# NSFW ONNX (backend) — laisser vides pour désactiver la classification automatique
NSFW_ONNX_MODEL_PATH = (os.environ.get('NSFW_ONNX_MODEL_PATH') or '').strip()
NSFW_ONNX_MODEL_URL = (os.environ.get('NSFW_ONNX_MODEL_URL') or '').strip()
# Libellés = ordre des sorties softmax du ONNX ( défaut mobilenet-nsfwjs )
NSFW_ONNX_CLASSES = (
    os.environ.get('NSFW_ONNX_CLASSES') or 'Drawing,Hentai,Neutral,Porn,Sexy'
).strip()
NSFW_ONNX_LAYOUT = (os.environ.get('NSFW_ONNX_LAYOUT') or 'NCHW').strip()
NSFW_ONNX_IMG_SIZE = int(os.environ.get('NSFW_ONNX_IMG_SIZE') or '224')
NSFW_ONNX_NORMALIZE = (os.environ.get('NSFW_ONNX_NORMALIZE') or 'imagenet').strip()
NSFW_TWOCLASS_UNSAFE_BIAS = float(os.environ.get('NSFW_TWOCLASS_UNSAFE_BIAS') or '0')

# ── Recherche (Phase 1 pg_trgm, Phase 2 Typesense) ───────────────────────────
# SEARCH_ENGINE=postgres (défaut) | typesense
SEARCH_ENGINE = (os.environ.get('SEARCH_ENGINE') or 'postgres').strip().lower()
SEARCH_USE_TRIGRAM = os.environ.get('SEARCH_USE_TRIGRAM', 'true').lower() in ('1', 'true', 'yes')
TYPESENSE_HOST = (os.environ.get('TYPESENSE_HOST') or '').strip()
TYPESENSE_API_KEY = (os.environ.get('TYPESENSE_API_KEY') or '').strip()
TYPESENSE_PROTOCOL = (os.environ.get('TYPESENSE_PROTOCOL') or 'http').strip()
TYPESENSE_PORT = int(os.environ.get('TYPESENSE_PORT') or '8108')
TYPESENSE_TIMEOUT_SECONDS = float(os.environ.get('TYPESENSE_TIMEOUT_SECONDS') or '2')

LOGGING = __import__('pinova_backend.observability.logging', fromlist=['build_logging_config']).build_logging_config(
    debug=DEBUG
)
