"""Constantes métier du système publicitaire Pinova."""

# Statuts
ADVERTISER_STATUS_PENDING = 'pending'
ADVERTISER_STATUS_ACTIVE = 'active'
ADVERTISER_STATUS_SUSPENDED = 'suspended'
ADVERTISER_STATUS_CHOICES = [
    (ADVERTISER_STATUS_PENDING, 'Pending'),
    (ADVERTISER_STATUS_ACTIVE, 'Active'),
    (ADVERTISER_STATUS_SUSPENDED, 'Suspended'),
]

CAMPAIGN_STATUS_DRAFT = 'draft'
CAMPAIGN_STATUS_ACTIVE = 'active'
CAMPAIGN_STATUS_PAUSED = 'paused'
CAMPAIGN_STATUS_ARCHIVED = 'archived'
CAMPAIGN_STATUS_CHOICES = [
    (CAMPAIGN_STATUS_DRAFT, 'Draft'),
    (CAMPAIGN_STATUS_ACTIVE, 'Active'),
    (CAMPAIGN_STATUS_PAUSED, 'Paused'),
    (CAMPAIGN_STATUS_ARCHIVED, 'Archived'),
]

CAMPAIGN_OBJECTIVE_AWARENESS = 'awareness'
CAMPAIGN_OBJECTIVE_TRAFFIC = 'traffic'
CAMPAIGN_OBJECTIVE_ENGAGEMENT = 'engagement'
CAMPAIGN_OBJECTIVE_APP_INSTALL = 'app_install'
CAMPAIGN_OBJECTIVE_CHOICES = [
    (CAMPAIGN_OBJECTIVE_AWARENESS, 'Awareness'),
    (CAMPAIGN_OBJECTIVE_TRAFFIC, 'Traffic'),
    (CAMPAIGN_OBJECTIVE_ENGAGEMENT, 'Engagement'),
    (CAMPAIGN_OBJECTIVE_APP_INSTALL, 'App install'),
]

BID_STRATEGY_CPM = 'cpm'
BID_STRATEGY_CPC = 'cpc'
BID_STRATEGY_CHOICES = [
    (BID_STRATEGY_CPM, 'CPM'),
    (BID_STRATEGY_CPC, 'CPC'),
]

BUDGET_TYPE_DAILY = 'daily'
BUDGET_TYPE_LIFETIME = 'lifetime'
BUDGET_TYPE_CHOICES = [
    (BUDGET_TYPE_DAILY, 'Daily'),
    (BUDGET_TYPE_LIFETIME, 'Lifetime'),
]

PACING_EVEN = 'even'
PACING_ASAP = 'asap'
PACING_CHOICES = [
    (PACING_EVEN, 'Even'),
    (PACING_ASAP, 'ASAP'),
]

AD_STATUS_DRAFT = 'draft'
AD_STATUS_ACTIVE = 'active'
AD_STATUS_PAUSED = 'paused'
AD_STATUS_REJECTED = 'rejected'
AD_STATUS_CHOICES = [
    (AD_STATUS_DRAFT, 'Draft'),
    (AD_STATUS_ACTIVE, 'Active'),
    (AD_STATUS_PAUSED, 'Paused'),
    (AD_STATUS_REJECTED, 'Rejected'),
]

AD_FORMAT_FEED_VIDEO = 'feed_video'
AD_FORMAT_FEED_IMAGE = 'feed_image'
AD_FORMAT_SIDEBAR_NATIVE = 'sidebar_native'
AD_FORMAT_EXPLORE_NATIVE = 'explore_native'
AD_FORMAT_CHOICES = [
    (AD_FORMAT_FEED_VIDEO, 'Feed video (native)'),
    (AD_FORMAT_FEED_IMAGE, 'Feed image (native)'),
    (AD_FORMAT_SIDEBAR_NATIVE, 'Sidebar native (web)'),
    (AD_FORMAT_EXPLORE_NATIVE, 'Explore / trending native'),
]

PLACEMENT_FEED_MOBILE = 'feed_mobile'
PLACEMENT_FEED_WEB = 'feed_web'
PLACEMENT_SIDEBAR_WEB = 'sidebar_web'
PLACEMENT_EXPLORE = 'explore'
PLACEMENT_CHOICES = [
    (PLACEMENT_FEED_MOBILE, 'Feed mobile'),
    (PLACEMENT_FEED_WEB, 'Feed web'),
    (PLACEMENT_SIDEBAR_WEB, 'Sidebar desktop web'),
    (PLACEMENT_EXPLORE, 'Explore / trending'),
]

INTEREST_KEY_TOPIC = 'topic'
INTEREST_KEY_HASHTAG = 'hashtag'
INTEREST_KEY_CATEGORY = 'category'
INTEREST_KEY_SEARCH = 'search'
INTEREST_KEY_TYPE_CHOICES = [
    (INTEREST_KEY_TOPIC, 'Topic'),
    (INTEREST_KEY_HASHTAG, 'Hashtag'),
    (INTEREST_KEY_CATEGORY, 'Category'),
    (INTEREST_KEY_SEARCH, 'Search'),
]

PENDING_EVENT_IMPRESSION = 'impression'
PENDING_EVENT_CLICK = 'click'
PENDING_EVENT_VIEW = 'view'
PENDING_EVENT_WATCH = 'watch'
PENDING_EVENT_TYPE_CHOICES = [
    (PENDING_EVENT_IMPRESSION, 'Impression'),
    (PENDING_EVENT_CLICK, 'Click'),
    (PENDING_EVENT_VIEW, 'View'),
    (PENDING_EVENT_WATCH, 'Watch'),
]

# Poids par défaut du ranking (tunable via settings)
DEFAULT_RANK_WEIGHT_BID = 0.22
DEFAULT_RANK_WEIGHT_RELEVANCE = 0.28
DEFAULT_RANK_WEIGHT_QUALITY = 0.22
DEFAULT_RANK_WEIGHT_FRESHNESS = 0.08
DEFAULT_RANK_WEIGHT_ENGAGEMENT_PRED = 0.12
DEFAULT_RANK_FATIGUE_PENALTY = 0.08
