# Generated by Django 6.0.4 on 2026-05-03 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_web_push'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Like'), ('save', 'Save'), ('follow', 'Follow'), ('comment', 'Comment'), ('welcome', 'Welcome'), ('payment', 'Payment'), ('plan_change', 'Plan Change'), ('system', 'System'), ('digest', 'Digest'), ('board_invite', 'Board invite'), ('scheduled_publish', 'Scheduled pin published')], max_length=20),
        ),
    ]
