# Generated by Django 6.0.4 on 2026-05-09 17:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fotos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_key', models.CharField(db_index=True, help_text='Format YYYY-MM', max_length=7, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('is_locked', models.BooleanField(default=False)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('auto_reset_enabled', models.BooleanField(default=True)),
                ('start_at', models.DateTimeField(db_index=True)),
                ('end_at', models.DateTimeField(db_index=True)),
                ('max_winners', models.PositiveSmallIntegerField(default=3)),
                ('leaderboard_display_pins', models.PositiveSmallIntegerField(default=10, help_text='Pins shown on the live leaderboard (one row per creator, best foto). Caps the public fotos API.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)])),
                ('distribution_mode', models.CharField(choices=[('fixed', 'Fixed'), ('custom', 'Custom'), ('percentage', 'Percentage')], default='percentage', max_length=20)),
                ('total_prize_pool', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('winner_1_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('winner_2_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('winner_3_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('distribution_weights_json', models.JSONField(blank=True, default=list)),
                ('weight_likes', models.FloatField(default=1.0)),
                ('weight_views', models.FloatField(default=0.15)),
                ('weight_shares', models.FloatField(default=3.0)),
                ('weight_saves', models.FloatField(default=2.0)),
                ('weight_comments', models.FloatField(default=2.5)),
                ('recency_decay_enabled', models.BooleanField(default=True)),
                ('decay_rate', models.FloatField(default=0.02)),
                ('virality_multiplier', models.FloatField(default=1.0)),
                ('share_boost_factor', models.FloatField(default=1.0)),
                ('max_actions_per_user_weight', models.PositiveIntegerField(default=20)),
                ('min_view_duration_seconds', models.PositiveIntegerField(default=2)),
                ('valid_view_time_threshold', models.PositiveIntegerField(default=2)),
                ('max_likes_per_user_per_pin', models.PositiveIntegerField(default=1)),
                ('comment_min_length', models.PositiveIntegerField(default=2)),
                ('trust_score_threshold', models.FloatField(default=0.4)),
                ('referral_defer_rewards', models.BooleanField(default=True, help_text='Si activé : aucun point parrain tant que le filleul ne passe pas les garde-fous (âge compte, actions, trust).')),
                ('referral_min_account_age_hours', models.PositiveIntegerField(default=12, help_text='Âge minimum du compte filleul (h) avant éligibilité aux points parrain.')),
                ('referral_min_engagement_actions', models.PositiveIntegerField(default=1, help_text='Nombre minimum d’interactions concours fotos valides (filleul) pour débloquer la récompense.')),
                ('referral_reward_delay_hours', models.PositiveIntegerField(default=1, help_text='Délai minimum après première activation email du filleul avant éligibilité aux points.')),
                ('referral_min_days_before_reward', models.PositiveIntegerField(default=2, help_text='Jours minimum après activation du parrainage avant points (0 = désactivé).')),
                ('referral_max_signups_per_ip_per_24h', models.PositiveIntegerField(default=40, help_text='Plafond inscriptions avec contexte IP identique sur 24 h (anti mass signup).')),
                ('referral_max_signups_per_device_per_24h', models.PositiveIntegerField(default=20, help_text='Plafond inscriptions avec même empreinte device sur 24 h.')),
                ('referral_max_referrals_per_referrer_per_24h', models.PositiveIntegerField(default=40, help_text='Plafond nouveaux filleuls attribués au même parrain sur 24 h.')),
                ('referral_referee_trust_threshold', models.FloatField(default=0.25, help_text='Trust minimum du filleul (0–1) pour créditer le parrain.')),
                ('referral_min_pins_published', models.PositiveIntegerField(default=0, help_text='Nombre minimum de fotos publics publiés par le filleul (0 = désactivé).')),
                ('notify_top_100', models.BooleanField(default=True)),
                ('notify_top_10', models.BooleanField(default=True)),
                ('notify_winner', models.BooleanField(default=True)),
                ('notify_leaderboard_rank_changes', models.BooleanField(default=True, help_text='Notify creators when their displayed contest rank (best foto) changes; uses anti-spam throttling.')),
                ('notify_rank_change_threshold', models.PositiveIntegerField(default=5)),
                ('leaderboard_refresh_interval', models.PositiveIntegerField(default=3, help_text='seconds')),
                ('websocket_broadcast_threshold', models.FloatField(default=0.2)),
                ('test_mode_enabled', models.BooleanField(default=False)),
                ('simulate_random_engagement', models.BooleanField(default=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contest_settings_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-contest_key'],
            },
        ),
        migrations.CreateModel(
            name='ContestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winners_json', models.JSONField(blank=True, default=list)),
                ('payout_json', models.JSONField(blank=True, default=list)),
                ('finalized_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('contest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='contests.contestsettings')),
            ],
            options={
                'ordering': ['-finalized_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaderboardEvent',
            fields=[
                ('sequence', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=32)),
                ('entity_type', models.CharField(db_index=True, max_length=16)),
                ('entity_id', models.PositiveIntegerField(db_index=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_events', to='contests.contestsettings')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='ContestInteractionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('like', 'Like'), ('view', 'View'), ('save', 'Save'), ('share', 'Share'), ('comment', 'Comment')], max_length=16)),
                ('dwell_seconds', models.PositiveIntegerField(default=0)),
                ('trust_score', models.FloatField(default=1.0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_valid', models.BooleanField(db_index=True, default=True)),
                ('invalid_reason', models.CharField(blank=True, default='', max_length=120)),
                ('score_delta', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_events', to=settings.AUTH_USER_MODEL)),
                ('pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_events', to='fotos.pin')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='contests.contestsettings')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['contest', 'interaction_type', '-created_at'], name='contests_co_contest_1a1b1f_idx'), models.Index(fields=['contest', 'pin', '-created_at'], name='contests_co_contest_43a3ca_idx'), models.Index(fields=['contest', 'actor', '-created_at'], name='contests_co_contest_4df8e1_idx')],
            },
        ),
        migrations.CreateModel(
            name='CreatorContestScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjusted_score', models.FloatField(db_index=True, default=0.0)),
                ('rank', models.PositiveIntegerField(db_index=True, default=0)),
                ('previous_rank', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_scores', to='contests.contestsettings')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_creator_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['rank', '-adjusted_score'],
                'unique_together': {('contest', 'creator')},
            },
        ),
        migrations.CreateModel(
            name='LeaderboardSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_type', models.CharField(choices=[('pin', 'Foto'), ('creator', 'Creator')], max_length=12)),
                ('rank', models.PositiveIntegerField()),
                ('entity_id', models.PositiveIntegerField()),
                ('score', models.FloatField(default=0.0)),
                ('captured_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='contests.contestsettings')),
            ],
            options={
                'ordering': ['-captured_at', 'rank'],
                'indexes': [models.Index(fields=['contest', 'snapshot_type', '-captured_at'], name='contests_le_contest_6effb5_idx')],
            },
        ),
        migrations.CreateModel(
            name='PinContestScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_score', models.FloatField(default=0.0)),
                ('adjusted_score', models.FloatField(db_index=True, default=0.0)),
                ('rank', models.PositiveIntegerField(db_index=True, default=0)),
                ('previous_rank', models.PositiveIntegerField(default=0)),
                ('total_likes', models.PositiveIntegerField(default=0)),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('total_saves', models.PositiveIntegerField(default=0)),
                ('total_shares', models.PositiveIntegerField(default=0)),
                ('total_comments', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pin_scores', to='contests.contestsettings')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_foto_scores', to=settings.AUTH_USER_MODEL)),
                ('pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_scores', to='fotos.pin')),
            ],
            options={
                'ordering': ['rank', '-adjusted_score'],
                'unique_together': {('contest', 'pin')},
            },
        ),
    ]
