# Generated by Django 6.0.5 on 2026-06-15 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_contestwinnerpayout'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contestwinnerpayout',
            new_name='contests_co_contest_dd15d5_idx',
            old_name='contests_con_contest_efb6e4_idx',
        ),
        migrations.AlterField(
            model_name='contestsettings',
            name='referral_min_engagement_actions',
            field=models.PositiveIntegerField(default=1, help_text="Nombre minimum d'interactions concours fotos valides (filleul) pour débloquer la récompense."),
        ),
    ]
